server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
  db:
    database: hm-user
    swagger:
      title: "黑马商城用户服务接口文档"
      package: com.hmall.user.controller
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
