server:
  port: 8080
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
      - /error
      - /favicon.ico
      - /v2/**
      - /v3/**
      - /swagger-resources/**
      - /webjars/**
      - doc.html
  sentinel:
    server-addr: localhost